### ISSUE TITLE
Proposal peer review-RoboCops

### ISSUE THREAD

**Issue by Peter-Yeh-coder** [INFO-526-S24/project-final-GraphicalGeniuses#1]
The following is the peer review of the project proposal by RoboCops. The team members that participated in this review are 

- Peter Yeh - @Peter-Yeh-coder
- Sachin Pandurang Patil - @sachin3115
- Arun Koundinya Parasa - @ArunKoundinya
- Surajit Pal - @sura789
- Christian Ortmann - @christian-ortmann
- Valérie Naa Dei Okine - @valerie-okine

- Describe the goal of the project.

Comparing and contrasting the performance Christiano Ronaldo and Leonel Messi across different countries over time using primarily geographical plots. 

- Describe the data used or collected.

Two .csv for each player from Kaggle and are identical in variables. There are 13 variables for each. Each variable is either a statistic or time. Exact details are shown in a table.

No details about data collection is mentioned beyond stating the data is readily available.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

Question: compare and contrast the performance over space and time.

Approach: side-by-side animation detailing the number of goals scored by each players geographically over time. Isolating competitions both players have participated in, and display on a world map and show how it changes dynamically through each season. Time frame is 2005-2020.

They also plan to make a secondary interactive map summarize the number of goals scored by each player in each country.

Time variable will be changed to date time objects, integers, or PosixCT. Replace NA's with no assist for goal_assist.

- Is there anything that is unclear from the proposal?

The type of layers for the geographical maps are unclear/unspecified in terms of how change will be visualized over time. For the interactive map, how detailed will it be (what countries play in, will it be a world map, etc.)

- Provide constructive feedback on how the team might be able to improve their project.

Be more specific in details and at what level of mapping (ie continent/world,/country/region)

Be mindful of animation length because if it too fast, hard to see (could also put a toggle bar).

Keep in mind that your datasets are of unequal length, so you may need to weigh your dataset values accordingly.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are interested in what insights we could learn such as where each player played their best and what type of competition they performed best in.

- Provide constructive feedback on any issues with file and/or code organization.

Post website. Make sure the repo passes all submit checks.

For table of dataset values, bold the name of the player as well.

- (Optional) Any further comments or feedback?

Fill out the readme in the data folder as well. Essentially copy paste your table of variable values.

**Comment by Bolajiadewal3** [comment]
Is there anything that is unclear from the proposal?

The type of layers for the geographical maps are unclear/unspecified in terms of how change will be visualized over time. For the interactive map, how detailed will it be (what countries play in, will it be a world map, etc.)

**We have specified now the layers of the map, a base layer and fill one to convey information; as well as how the seasons will dictate the changes to the animation. The interactivity of the interactive map has been explained - detailing what exactly will be interactive about the map. We have also stated that the map used will be a global one.**


Provide constructive feedback on how the team might be able to improve their project.
Be more specific in details and at what level of mapping (ie continent/world,/country/region)

Be mindful of animation length because if it too fast, hard to see (could also put a toggle bar).

Keep in mind that your datasets are of unequal length, so you may need to weigh your dataset values accordingly.

**We have stated that the animation length will be selected to allow for enough time to view and understand the data presented each season. We have additionally explained that we will go forward from the 2004 season, to combat the fact that the dataset are uneven in length**



Provide constructive feedback on any issues with file and/or code organization.
Post website. Make sure the repo passes all submit checks.

For table of dataset values, bold the name of the player as well.

(Optional) Any further comments or feedback?
Fill out the readme in the data folder as well. Essentially copy paste your table of variable values.

**We have emboldened the names of the players in the table, and filled out the readme data.**

**Thank you for your feedback, we have made changes accordingly**
